[project]
name = "portfolio-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pylint>=3.3.5",
    "pyright>=1.1.396",
    "ruff>=0.11.0",
    "sphinx>=8.2.3",
    "torch>=2.6.0",
]
